In [19]:
import numpy as np

def hessian(x):
    """
    Calculate the hessian matrix with finite differences
    Parameters:
       - x : ndarray
    Returns:
       an array of shape (x.dim, x.ndim) + x.shape
       where the array[i, j, ...] corresponds to the second derivative x_ij
    """
    x_grad = np.gradient(x) 
    hessian = np.empty((x.ndim, x.ndim) + x.shape, dtype=x.dtype) 
    for k, grad_k in enumerate(x_grad):
        # iterate over dimensions
        # apply gradient again to every component of the first derivative.
        tmp_grad = np.gradient(grad_k) 
        for l, grad_kl in enumerate(tmp_grad):
            hessian[k, l, :, :] = grad_kl
    return hessian

#x = np.random.randn(2, 2)
x = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
hessian(x)

array([[[[ 0,  0,  0],
         [ 0,  0,  0]],

        [[-3,  0,  2],
         [-3,  0,  2]]],


       [[[-3,  0,  2],
         [-3,  0,  2]],

        [[ 0,  0,  0],
         [ 2,  2,  2]]]])

In [21]:
print (x)

[[1 2 3]
 [4 2 5]]
